### ISSUE TITLE
Weights link broken

### ISSUE THREAD

**Issue by egirgin** [levan92/occlusion-copy-paste#1]
Hello,

I'd like to test your method. However none of the links for weights you provided in the results table are working. Can you check the Google Drive files and reshare the file?

**Comment by levan92** [comment]
Hi! Thank you so much for bringing this up. The gdrive links are broken as my previous school gdrive account got deactivated and I forgotten to re-upload them. I am currently on holiday, will upload them as soon as possible. Will let you know once they're up. Sorry about that!

**Comment by levan92** [comment]
Any specific model you're looking for first? If it's urgent, I could get my teammates to help me upload the weights for a particular model, otherwise if you can wait till next week, I'll upload the weights all at once then.

**Comment by egirgin** [comment]
Next week is OK for me. Thank you for the quick response :)

**Comment by levan92** [comment]
Sorry for the delay! I've updated the google drive links on the README (commit 62b8cb63726b46eb2b89a15a2f9d8efce0670702).
